#!/usr/bin/env bash
# To install nginx on my web server that will print hello world

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
